package lecho.lib.hellocharts.model;

import android.graphics.Typeface;
import java.util.ArrayList;
import java.util.List;
import lecho.lib.hellocharts.formatter.AxisValueFormatter;
import lecho.lib.hellocharts.formatter.SimpleAxisValueFormatter;
import lecho.lib.hellocharts.util.ChartUtils;

public class Axis {
    public static final int DEFAULT_MAX_AXIS_LABEL_CHARS = 3;
    public static final int DEFAULT_TEXT_SIZE_SP = 12;
    private AxisValueFormatter formatter = new SimpleAxisValueFormatter();
    private boolean hasLines = false;
    private boolean hasSeparationLine = true;
    private boolean hasTiltedLabels = false;
    private boolean isAutoGenerated = true;
    private boolean isInside = false;
    private int lineColor = ChartUtils.DEFAULT_DARKEN_COLOR;
    private int maxLabelChars = 3;
    private String name;
    private int textColor = -3355444;
    private int textSize = 12;
    private Typeface typeface;
    private List<AxisValue> values = new ArrayList();

    public Axis() {
    }

    public Axis(List<AxisValue> values2) {
        setValues(values2);
    }

    public Axis(Axis axis) {
        this.name = axis.name;
        this.isAutoGenerated = axis.isAutoGenerated;
        this.hasLines = axis.hasLines;
        this.isInside = axis.isInside;
        this.textColor = axis.textColor;
        this.lineColor = axis.lineColor;
        this.textSize = axis.textSize;
        this.maxLabelChars = axis.maxLabelChars;
        this.typeface = axis.typeface;
        this.formatter = axis.formatter;
        this.hasSeparationLine = axis.hasSeparationLine;
        for (AxisValue axisValue : axis.values) {
            this.values.add(new AxisValue(axisValue));
        }
    }

    public static Axis generateAxisFromRange(float start, float stop, float step) {
        List<AxisValue> values2 = new ArrayList<>();
        float value = start;
        while (value <= stop) {
            values2.add(new AxisValue(value));
            value += step;
        }
        return new Axis(values2);
    }

    public static Axis generateAxisFromCollection(List<Float> axisValues) {
        List<AxisValue> values2 = new ArrayList<>();
        int index = 0;
        for (Float f : axisValues) {
            values2.add(new AxisValue(f.floatValue()));
            index++;
        }
        return new Axis(values2);
    }

    public static Axis generateAxisFromCollection(List<Float> axisValues, List<String> axisValuesLabels) {
        if (axisValues.size() != axisValuesLabels.size()) {
            throw new IllegalArgumentException("Values and labels lists must have the same size!");
        }
        List<AxisValue> values2 = new ArrayList<>();
        int index = 0;
        for (Float f : axisValues) {
            values2.add(new AxisValue(f.floatValue()).setLabel(axisValuesLabels.get(index)));
            index++;
        }
        return new Axis(values2);
    }

    public List<AxisValue> getValues() {
        return this.values;
    }

    public Axis setValues(List<AxisValue> values2) {
        if (values2 == null) {
            this.values = new ArrayList();
        } else {
            this.values = values2;
        }
        this.isAutoGenerated = false;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public Axis setName(String name2) {
        this.name = name2;
        return this;
    }

    public boolean isAutoGenerated() {
        return this.isAutoGenerated;
    }

    public Axis setAutoGenerated(boolean isAutoGenerated2) {
        this.isAutoGenerated = isAutoGenerated2;
        return this;
    }

    public boolean hasLines() {
        return this.hasLines;
    }

    public Axis setHasLines(boolean hasLines2) {
        this.hasLines = hasLines2;
        return this;
    }

    public int getTextColor() {
        return this.textColor;
    }

    public Axis setTextColor(int color) {
        this.textColor = color;
        return this;
    }

    public boolean isInside() {
        return this.isInside;
    }

    public Axis setInside(boolean isInside2) {
        this.isInside = isInside2;
        return this;
    }

    public int getLineColor() {
        return this.lineColor;
    }

    public Axis setLineColor(int lineColor2) {
        this.lineColor = lineColor2;
        return this;
    }

    public int getTextSize() {
        return this.textSize;
    }

    public Axis setTextSize(int textSize2) {
        this.textSize = textSize2;
        return this;
    }

    public int getMaxLabelChars() {
        return this.maxLabelChars;
    }

    public Axis setMaxLabelChars(int maxLabelChars2) {
        if (maxLabelChars2 < 0) {
            maxLabelChars2 = 0;
        } else if (maxLabelChars2 > 32) {
            maxLabelChars2 = 32;
        }
        this.maxLabelChars = maxLabelChars2;
        return this;
    }

    public Typeface getTypeface() {
        return this.typeface;
    }

    public Axis setTypeface(Typeface typeface2) {
        this.typeface = typeface2;
        return this;
    }

    public AxisValueFormatter getFormatter() {
        return this.formatter;
    }

    public Axis setFormatter(AxisValueFormatter formatter2) {
        if (formatter2 == null) {
            this.formatter = new SimpleAxisValueFormatter();
        } else {
            this.formatter = formatter2;
        }
        return this;
    }

    public Axis setHasSeparationLine(boolean hasSeparationLine2) {
        this.hasSeparationLine = hasSeparationLine2;
        return this;
    }

    public boolean hasSeparationLine() {
        return this.hasSeparationLine;
    }

    public boolean hasTiltedLabels() {
        return this.hasTiltedLabels;
    }

    public Axis setHasTiltedLabels(boolean hasTiltedLabels2) {
        this.hasTiltedLabels = hasTiltedLabels2;
        return this;
    }
}
