package lecho.lib.hellocharts.formatter;

import lecho.lib.hellocharts.model.AxisValue;

public interface AxisValueFormatter {
    int formatValueForAutoGeneratedAxis(char[] cArr, float f, int i);

    int formatValueForManualAxis(char[] cArr, AxisValue axisValue);
}
