package dji.common.flightcontroller.rtk;

public enum NetworkServiceChannelState {
    RTCM_CONNECTED,
    RTCM_NORMAL,
    RTCM_USER_HAS_ACTIVATE,
    RTCM_USER_ACCOUNT_EXPIRES_SOON,
    RTCM_USE_DEFAULT_MOUNTPOINT,
    RTCM_AUTH_FAILED,
    RTCM_USER_NOT_BOUND,
    RTCM_USER_NOT_ACTIVATED,
    RTCM_USER_ACCOUNT_EXPIRED,
    RTCM_ILLEGAL_UTC_TIME,
    DISABLED,
    NETWORK_NOT_REACHABLE,
    AIRCRAFT_DISCONNECTED,
    LOGIN_FAILURE,
    READY,
    TRANSMITTING,
    DISCONNECTED,
    UNKNOWN
}
